[target.aarch64-linux-android]
linker = "/Users/wynnetran/Library/Android/sdk/ndk/27.1.12297006/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android21-clang"
rustflags = ["-Clink-arg=-fuse-ld=lld"]
